from __future__ import annotations

from xinyidai_agent.capabilities.base import CapabilityPolicy


def default_capability_catalog() -> list[CapabilityPolicy]:
    return [
        CapabilityPolicy(
            capability_id="knowledge.policy.read",
            scene="KNOWLEDGE_QA",
            standard_intent="POLICY_OR_PRODUCT_QA",
            description="检索政策、产品、准入规则等知识库证据。",
            raw_intent_aliases=[
                "POLICY_OR_PRODUCT_QA",
                "POLICY_ELIGIBILITY_QA",
                "query_eligibility_criteria",
                "query_policy",
                "product_policy_qa",
            ],
            allowed_tools=["rag_search"],
            allowed_tool_categories=["knowledge"],
            risk_level="read_only",
        ),
        CapabilityPolicy(
            capability_id="credit.limit.read",
            scene="DATA_QUERY",
            standard_intent="CREDIT_LIMIT_QUERY",
            description="查询企业授信额度、可贷额度等只读信用数据。",
            raw_intent_aliases=[
                "CREDIT_LIMIT_QUERY",
                "CREDIT_ELIGIBILITY_QUERY",
                "query_credit_limit",
                "query_credit_amount",
            ],
            required_slots=["company_name"],
            allowed_tools=["query_credit_amount"],
            allowed_tool_categories=["data_query"],
            risk_level="read_only",
        ),
        CapabilityPolicy(
            capability_id="authorization.link.create",
            scene="AUTHORIZATION",
            standard_intent="CREATE_AUTHORIZATION_LINK",
            description="生成企业授权链接，用于企业授权信用数据查询。",
            raw_intent_aliases=[
                "CREATE_AUTHORIZATION_LINK",
                "generate_company_authorization_link",
                "create_authorization_url",
                "authorize_credit_data",
            ],
            required_slots=["company_name"],
            allowed_tools=["create_authorization_link"],
            allowed_tool_categories=["authorization"],
            risk_level="link_create",
            confirmation_required=True,
        ),
        CapabilityPolicy(
            capability_id="application.draft.create",
            scene="LOAN_APPLY",
            standard_intent="CREATE_APPLICATION",
            description="创建贷款申请草稿，后续需要企业授权后继续提交。",
            raw_intent_aliases=[
                "CREATE_APPLICATION",
                "create_application_draft",
                "start_loan_application",
            ],
            required_slots=["company_name", "product_name"],
            allowed_tools=["search_product", "create_application", "create_authorization_link"],
            allowed_tool_categories=["knowledge", "application", "authorization"],
            risk_level="state_create",
            confirmation_required=True,
        ),
        CapabilityPolicy(
            capability_id="application.status.read",
            scene="APPLICATION_STATUS",
            standard_intent="APPLICATION_STATUS_QUERY",
            description="查询贷款申请办理状态。",
            raw_intent_aliases=["APPLICATION_STATUS_QUERY", "query_application_status"],
            required_slots=["application_id"],
            allowed_tools=["query_application_status"],
            allowed_tool_categories=["status"],
            risk_level="read_only",
        ),
        CapabilityPolicy(
            capability_id="smalltalk.respond",
            scene="SMALLTALK",
            standard_intent="SMALLTALK",
            description="普通闲聊或助手能力说明，不开放业务工具。",
            raw_intent_aliases=["SMALLTALK", "assistant_capability_intro"],
            risk_level="read_only",
        ),
        CapabilityPolicy(
            capability_id="unknown.clarify",
            scene="UNKNOWN",
            standard_intent="UNKNOWN",
            description="无法确认用户业务意图时追问。",
            raw_intent_aliases=["UNKNOWN", "LOW_CONFIDENCE"],
            risk_level="read_only",
        ),
    ]
